# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20171128_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_provider', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='bio',
            name='resume',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.ProviderProfile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='courses',
            field=models.ManyToManyField(through='user_profile.CourseStatus', to='user_profile.Course'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Provider'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
