# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20171128_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('c', 'completed'), ('i', 'in_progress')], max_length=1),
        ),
    ]
