# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20171130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'completed'), (0, 'in_progress')], max_length=1),
        ),
    ]
